from src.routers.auth_router import auth_router
from src.routers.user_router import users_router
from src.routers.tenant_router import tenant_router
from src.routers.property_router import property_router
from src.routers.real_estate_router import real_estate_router
from src.routers.guarantee_router import guarantee_router
from src.routers.contract_router import contract_router
from src.routers.payment_router import payment_router
from src.routers.extract_batch_router import extract_batch_router
from src.routers.analysis_router import analysis_router